Repository Sanium/sanium.rest, pull requests merged in 2020-03, with the labels that each got.

#38 L-38 Usunięcie path_to_logo z tworzenia Usera
  app/User.php
  database/migrations/2020_03_23_225929_alter_employers_table.php
Labels: bug

#39 L-39 NIe wyświetlać kiedy NULL
  resources/views/dashboard.blade.php
Labels: bug

#40 L-40 Zamiana przycisku profil na dashboard w widoku dla mobilek
  resources/views/layouts/app.blade.php
Labels: bug

#41 L-41 Fix formularza edit profil
  resources/views/auth/register.blade.php
  resources/views/profile/employer/edit.blade.php
Labels: bug

#42 L-42 Website w Ofercie nie pobiera danych z bazy
  app/Http/Controllers/OfferController.php
Labels: bug

#46 L-46 Błąd przy tworzeniu Oferty
  app/Http/Controllers/OfferController.php
  public_html/css/app.css
  public_html/js/app.js
  resources/js/app.js
  resources/sass/typography.scss
  resources/views/layouts/app.blade.php
  resources/views/offer/edit.blade.php
Labels: bug

#30 L-30 Reorganizacja templatów
  resources/views/components/navbar.blade.php
  resources/views/dashboard.blade.php
  resources/views/imports/css.blade.php
  resources/views/imports/js.blade.php
  resources/views/layouts/app.blade.php
  resources/views/offer/edit.blade.php
  resources/views/profile/employer/edit.blade.php
  resources/views/welcome.blade.php
Labels: refactoring

#44 L-44 Profil administratora
  .phpstorm.meta.php
  app/Admin.php
  app/Currency.php
  app/Employer.php
  app/Employment.php
  app/Experience.php
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/HomeController.php
  app/ProfileInterface.php
  app/Technology.php
  app/User.php
  database/migrations/2020_03_20_194734_create_technologies_table.php
  database/migrations/2020_03_20_194837_create_experiences_table.php
  database/migrations/2020_03_20_194904_create_employments_table.php
  database/migrations/2020_03_20_195436_create_currencies_table.php
  database/migrations/2020_03_20_195624_create_offers_table.php
  database/migrations/2020_03_22_222947_add_slugs_to_offer_params_table.php
  database/migrations/2020_03_26_132617_create_admins_table.php
  database/seeds/AdminSeeder.php
  database/seeds/DatabaseSeeder.php
  database/seeds/EmployersTableSeeder.php
  database/seeds/OfferParamsSeeder.php
  database/seeds/UsersTableSeeder.php
  routes/web.php
  tests/Unit/UserAdminTest.php
  tests/Unit/UserEmployerTest.php
Labels: enhancement

#49 L-49 Zmiana frameworka
  public_html/css/app.css
  public_html/js/app.js
  resources/sass/app.scss
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
Labels: refactoring

#50 L-50 Fix js mdbootstrap
  package-lock.json
  package.json
  webpack.mix.js
Labels: bug

#51 L-51 Refactoring rejestracji
  app/Http/Controllers/Auth/RegisterController.php
  public_html/css/app.css
  public_html/js/app.js
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/components/navbar.blade.php
Labels: refactoring

#52 L-52 Refactor dashboardu
  public_html/js/app.js
  resources/views/dashboard.blade.php
Labels: refactoring

#53 L-53 Refactor edycji oferty
  app/Http/Controllers/OfferController.php
  database/migrations/2020_03_31_173330_alter_offer_table_disclaimer_delete.php
  public_html/css/app.css
  public_html/fonts/vendor/dropify/dist/dropify.eot
  public_html/fonts/vendor/dropify/dist/dropify.svg
  public_html/fonts/vendor/dropify/dist/dropify.ttf
  public_html/fonts/vendor/dropify/dist/dropify.woff
  public_html/fonts/vendor/summernote/dist/summernote.eot
  public_html/fonts/vendor/summernote/dist/summernote.ttf
  public_html/fonts/vendor/summernote/dist/summernote.woff
  public_html/fonts/vendor/summernote/dist/summernote.woff2
  public_html/js/app.js
  public_html/js/app.js.LICENSE.txt
  resources/sass/app.scss
  resources/views/layouts/main.blade.php
  resources/views/offer/edit.blade.php
  webpack.mix.js
Labels: refactoring
