Repository Sanium/sanium.rest, pull requests merged in 2020-05, with the labels that each got.

#74 L-74 Dodanie ważności oferty 30 dni
  app/Http/Resources/OfferResource.php
  app/Offer.php
  database/migrations/2020_05_11_170951_update_offer_expires_at_date.php
  tests/Unit/OfferTest.php
Labels: enhancement

#73 L-73 Nie wyświetlanie wygaszonych ofert na froncie
  app/Http/Controllers/OfferController.php
Labels: enhancement

#72 L-72 Monit w dashboardzie o wygaśnięciu oferty
  app/Offer.php
  resources/lang/pl.json
  resources/views/dashboard.blade.php
Labels: enhancement

#75 L-75 Odświeżanie oferty z dashboardu
  app/Http/Controllers/OfferController.php
  app/Offer.php
  resources/lang/pl.json
  resources/views/dashboard.blade.php
  routes/web.php
Labels: enhancement

#60 L-60 Dodanie notyfikacji o udanej rejestracji oraz mailu z potwierdzeniem
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Auth/VerificationController.php
  resources/lang/pl.json
Labels: bug

#63 L-63 Dodanie widoku rejestracji użytkownika
  resources/lang/pl.json
  resources/views/auth/register.blade.php
Labels: enhancement

#65 L-65 Modyfikacja kontrolera rejestracji - dodanie użytkowników
  app/Http/Controllers/Auth/RegisterController.php
  resources/views/auth/register.blade.php
  resources/views/components/navbar.blade.php
  routes/web.php
Labels: enhancement

#76 L-76 Roszady w templatach
  app/Admin.php
  app/Client.php
  app/Employer.php
  app/Http/Controllers/HomeController.php
  app/ProfileInterface.php
  app/User.php
  resources/views/profile/client/dashboard.blade.php
  resources/views/profile/client/edit.blade.php
  resources/views/profile/employer/dashboard.blade.php
Labels: cleanup

#68 L-68 Kontroler profilu użytkownika
  app/Client.php
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/EmployerController.php
  app/Http/Controllers/HomeController.php
  app/Policies/ClientPolicy.php
  resources/lang/pl.json
  resources/views/components/navbar.blade.php
  resources/views/profile/client/dashboard.blade.php
  resources/views/profile/client/edit.blade.php
  routes/web.php
Labels: enhancement

#66 L-66 Dashboard dla użytkowników
  resources/views/profile/client/dashboard.blade.php
Labels: enhancement

#78 L-78 Widok ostatnich aplikacji w dashboardzie firmy
  resources/lang/pl.json
  resources/sass/helper.scss
  resources/views/profile/employer/dashboard.blade.php
Labels: enhancement

#80 L-80 Błąd rejestracji użytkownika
  .gitignore
  .phpstorm.meta.php
  app/Admin.php
  app/Client.php
  app/Currency.php
  app/Employer.php
  app/Employment.php
  app/Experience.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Auth/VerificationController.php
  app/JobOfferResponse.php
  app/Offer.php
  app/Role.php
  app/Technology.php
  app/User.php
  resources/lang/pl.json
  resources/views/auth/register.blade.php
  tests/Unit/UserAdminTest.php
  tests/Unit/UserEmployerTest.php
Labels: bug, cleanup

#81 L-81 Dodanie użytkowników w Admin Panelu
  app/Http/Controllers/AdminController.php
  resources/lang/pl.json
  resources/views/admin/dashboard.blade.php
  resources/views/admin/users.blade.php
  resources/views/layouts/admin.blade.php
  routes/web.php
Labels: enhancement

#71 L-71 Wyświetlanie wysłanych aplikacji w dashboardzie Pracodawcy
  resources/views/profile/employer/dashboard.blade.php
Labels: enhancement

#70 L-70 Rejestrowanie wysłanych aplikacji w ofercie
  app/Client.php
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/JobOfferResponseController.php
  app/JobOfferResponse.php
  routes/web.php
Labels: enhancement

#83 L-83 Lista aplikacji w dashboardzie użytkownika
  app/Http/Controllers/HomeController.php
  resources/lang/pl.json
  resources/views/profile/client/dashboard.blade.php
  resources/views/profile/employer/dashboard.blade.php
  routes/web.php
Labels: enhancement

#79 L-79 Błąd rejestracji, gdy tabela roli użytkowników jest pusta
  app/Http/Controllers/Auth/RegisterController.php
  app/User.php
  resources/lang/pl.json
Labels: bug

#69 L-69 Szybkie aplikowanie
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/JobOfferResponseController.php
  resources/lang/pl.json
  resources/lang/pl/validation.php
  resources/views/welcome.blade.php
Labels: enhancement

#85 L-85 Puste tabele
  resources/lang/pl.json
  resources/views/profile/client/dashboard.blade.php
  resources/views/profile/employer/dashboard.blade.php
Labels: enhancement

#87 L-87 Refaktor roli
  app/Http/Controllers/Auth/RegisterController.php
  app/Role.php
  app/User.php
  database/migrations/2020_05_20_174419_users_extend_role.php
  database/seeds/AdminSeeder.php
  tests/Unit/JobOfferResponseTest.php
  tests/Unit/UserAdminTest.php
  tests/Unit/UserClientTest.php
  tests/Unit/UserEmployerTest.php
Labels: refactoring

#86 L-86 Admin panel update
  app/Http/Controllers/AdminController.php
  app/Role.php
  app/User.php
  resources/views/admin/dashboard.blade.php
  resources/views/admin/offers.blade.php
  resources/views/admin/users.blade.php
  routes/web.php
Labels: enhancement
